### PR TITLE
Add aws:elasticbeanstalk:xray to EB command options

### PR DESCRIPTION
**Pull request by lvdh**
*Issue #, if available:*

No issue # (small change)

*Description of changes:*

Add Elastic Beanstalk command option `aws:elasticbeanstalk:xray`.

For reference: https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-beanstalk.html

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lvdh** [comment]
Note: I tested this EB command option through Terraform (which, afaik, uses the AWS API to manage AWS resources). When not defining this option, the resulting stack has X-Ray integration enabled by default. For this reason, I set the default option value to `true`. By all means, feel free to change this as necessary.

**Comment by dankhen** [comment]
Hi @lvdh ,
This namespace and the option in it are already documented as [Platform Specific Options](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-specific.html).
I'll make sure this is correct; leaving the PR open for now.

**Comment by dankhen** [comment]
Any option involving code running on the instance is implemented on a per-platform basis. X-ray is such a case - it involves the X-ray demon running on your instances. Therefore, documenting it as a platform-specific option is the correct way to go.

**Comment by lvdh** [comment]
I missed the Platform Specific Options. Thank you for pointing those out, @dankhen.

**Pull request closed without merging**
