### PR TITLE
Correct all the steps number and some indentions

### PR DESCRIPTION
**Pull request by fbukevin**
*Issue #, if available:*
no

*Description of changes:*
**Modification 1**
Original version has wrong step number in source code. 
For example,

```markdown
**To launch an RDS DB instance in a default VPC**

1. Open the [RDS console](https://console.aws.amazon.com/rds/home)\.

1. Choose **Instances** in the navigation pane\.

1. Choose **Launch DB Instance**\.

1. Choose a **DB Engine** and preset configuration\.
```

Even though markdown interpreter of GitHub can recognize and display correct serial number, it should be corrected like this:

```markdown
**To launch an RDS DB instance in a default VPC**

1. Open the [RDS console](https://console.aws.amazon.com/rds/home)\.

2. Choose **Instances** in the navigation pane\.

3. Choose **Launch DB Instance**\.

4. Choose a **DB Engine** and preset configuration\.
```

**Modification 2**

This three statements in original document is confused due to incorrect indentions.

```markdown
1. Modify the configuration files in the `.ebextensions` folder with the IDs of your default VPC and subnets, and your public IP address\.

1. The `.ebextensions/efs-create.config` file creates an EFS file system and mount points in each Availability Zone/subnet in your VPC\. Identify your default VPC and subnet IDs in the Amazon VPC console\.

   The `.ebextensions/dev.config` file restricts access to your environment to your IP address to protect it during the WordPress installation process\. Replace the placeholder IP address near the top of the file with your public IP address\.
```

For better reading, it should be corrected to:

```markdown
1. Modify the configuration files in the `.ebextensions` folder with the IDs of your default VPC and subnets, and your public IP address\.

  * The `.ebextensions/efs-create.config` file creates an EFS file system and mount points in each Availability Zone/subnet in your VPC\. Identify your default VPC and subnet IDs in the Amazon VPC console\.

  * The `.ebextensions/dev.config` file restricts access to your environment to your IP address to protect it during the WordPress installation process\. Replace the placeholder IP address near the top of the file with your public IP address\.

```

**Modification 3**

```markdown
8. Create a ZIP file from the files and folders in the `wordpress-beanstalk` folder \(not the parent directory\), using one of the following methods, depending on your operating system:

   9. Windows — In Windows Explorer, select the files and folders, right\-click, and then choose **Send to**, **Compressed \(zipped\) Folder**\. Name the file `wordpress-x.y.z.zip`, where `x.y.z` is the version of WordPress\.

   \-\-OR\-\-

   Mac OS X and Linux — Use the following command, where `x.y.z` is the version of WordPress:

   zip -r ../wordpress-x.y.z.zip .
```

For better reading, it should be:

```markdown
8. Create a ZIP file from the files and folders in the `wordpress-beanstalk` folder \(not the parent directory\), using one of the following methods, depending on your operating system:

   * Windows — In Windows Explorer, select the files and folders, right\-click, and then choose **Send to**, **Compressed \(zipped\) Folder**\. Name the file `wordpress-x.y.z.zip`, where `x.y.z` is the version of WordPress\.

   \-\-OR\-\-

   * Mac OS X and Linux — Use the following command, where `x.y.z` is the version of WordPress:

   zip -r ../wordpress-x.y.z.zip .
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dankhen** [comment]
Thanks @fbukevin. I can see how these bits of markdown can be confusing... however, they are all actually correct markdown, and render correctly in the resulting page. You can look at [the result](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/master/doc_source/php-hawordpress-tutorial.md), or compare to [the source page on our web site](https://alpha-docs-aws.amazon.com/elasticbeanstalk/latest/dg/php-hawordpress-tutorial.htm); you'll see that in both cases the rendering is correct.

For example, using the same number, e.g. `1. `, on all numbered items is correct markdown for a numbered list. You can use any numbers in fact; the rendering will give them the correct ascending order.

Also, markdown files that you see in this repo are actually generated by our build system from our sources, so even if I merged your changes, they would be overridden again once we deployed our next build to the repo.

I will therefore close the PR. Thanks for reviewing!

**Comment by fbukevin** [comment]
Hi @dankhen. Thanks for your reply. But I checked the result you provided or the official document, both of them have wrong rendering. I will keep my version for your reference in the future.

**Comment by dankhen** [comment]
Thanks @fbukevin. Reopening the PR for now, as I'd like to understand your findings. Can you please explain what you are seeing that's wrong? When I look at the numbering, it seems to be correct.

**Comment by fbukevin** [comment]
Hi @dankhen, please check out my screenshot for what I mentioned in modification 2 and 3. This is what I see it "the result" link.

screenshot 2018-03-16 09 43 32

I think this could make some confusion for customer. I also had confusion when I was doing some replication to troubleshoot for customer issue.

**Comment by dankhen** [comment]
Oh yes, you're right - these two changes make sense.
I will merge the PR. Notice that I will later make a similar change in our sources, and once I re-publish to GitHub, the resulting generated markdown might end up not being exactly what you suggested. It will render similarly, though.
Thanks again for your effort!

**Pull request merged**
